/* Generated By:JavaCC: Do not edit this line. MessageParserConstants.java */
package ca.utoronto.msrg.padres.common.message.parser;

public interface MessageParserConstants {

  int EOF = 0;
  int CLASS = 5;
  int COMMA = 6;
  int EQ = 7;
  int SEMICOLON = 8;
  int COLON = 9;
  int ISPRESENT = 10;
  int SOPERATOR = 11;
  int IOPERATOR = 12;
  int COPERATOR = 13;
  int ANAME = 14;
  int TIMEFORMAT = 15;
  int AVALZEROINT = 16;
  int AVALSTR = 17;
  int AVALLONG = 18;
  int AVALDOUBLE = 19;
  int SVARIABLE = 20;
  int IVARIABLE = 21;
  int IVAR = 22;
  int SVAR = 23;
  int FVAR = 24;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"class\"",
    "\",\"",
    "\"eq\"",
    "\";\"",
    "\":\"",
    "\"isPresent\"",
    "<SOPERATOR>",
    "<IOPERATOR>",
    "<COPERATOR>",
    "<ANAME>",
    "<TIMEFORMAT>",
    "<AVALZEROINT>",
    "<AVALSTR>",
    "<AVALLONG>",
    "<AVALDOUBLE>",
    "<SVARIABLE>",
    "<IVARIABLE>",
    "<IVAR>",
    "<SVAR>",
    "<FVAR>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
  };

}
